
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author java3
 */
public class zimmetListesi extends javax.swing.JFrame {

    /**
     * Creates new form zimmetListesi
     */
    public zimmetListesi() {
        initComponents();
        comboboxDoldur();
        tabloDoldur();
        urunIlDoldur();
        ilceDoldur();
        subeDoldur();
        personelDoldur();
    }
    ArrayList<String> zimIdler = new ArrayList<String>();

    public void comboboxDoldur() {

        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        DefaultComboBoxModel dc2 = new DefaultComboBoxModel();

        for (int i = 1; i <= 10; i++) {

            dc2.addElement(i);
            dc.addElement(i);

        }

        jComboBox6.setModel(dc2);
        jComboBox8.setModel(dc);

    }

    public void tabloDoldur() {

        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Zimmet Adı");
        dt.addColumn("Şube");
        dt.addColumn("Personel");
        dt.addColumn("Adet");
        dt.addColumn("Tarih");
        jTable1.setModel(dt);
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        DB db = new DB();
        
        try {

            ResultSet rs = db.baglan().executeQuery("Select * from zimmetler left join personeller on personeller.personel_id=zimmetler.zim_personel_id left join subeler on zimmetler.zim_sube_id=subeler.sube_id left join urunler on zimmetler.zim_urun_id=urunler.urun_id");
            while (rs.next()) {
                zimIdler.add(rs.getString("zim_id"));
                dt.addRow(new String[]{rs.getString("urun_adi"), rs.getString("sube_adi"), rs.getString("personel_adi") + " " + rs.getString("personel_soyadi"), rs.getString("zim_urun_adet"), rs.getString("zim_tarih")});

            }
            jTable1.setModel(dt);
            db.kapat();
        } catch (Exception e) {

            System.err.println("Tablo doldurma hatası: " + e);

        }

    }

    ArrayList<String> urId = new ArrayList<String>();
    ArrayList<String> ilId = new ArrayList<String>();
    ArrayList<String> ilceId = new ArrayList<String>();
    ArrayList<String> subeId = new ArrayList<String>();
    ArrayList<String> perId = new ArrayList<String>();
    ArrayList<String> ilceId2 = new ArrayList<String>();
    ArrayList<String> subeId2 = new ArrayList<String>();
    ArrayList<String> perId2 = new ArrayList<String>();

    public void urunIlDoldur() {

        DB db = new DB();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        DefaultComboBoxModel dc2 = new DefaultComboBoxModel();
        DefaultComboBoxModel dc3 = new DefaultComboBoxModel();
        DefaultComboBoxModel dc4 = new DefaultComboBoxModel();
        DefaultComboBoxModel dc5 = new DefaultComboBoxModel();
        DefaultComboBoxModel dc6 = new DefaultComboBoxModel();
        try {

            ResultSet rs = db.baglan().executeQuery("Select * from urunler");

            while (rs.next()) {

                dc.addElement(rs.getString("urun_adi"));
                dc5.addElement(rs.getString("urun_adi"));
                urId.add(rs.getString("urun_id"));
            }

            rs = db.baglan().executeQuery("select * from sehirler");
            while (rs.next()) {

                dc2.addElement(rs.getString("sehir_adi"));
                dc4.addElement(rs.getString("sehir_adi"));
                ilId.add(rs.getString("sehir_id"));
            }

            jComboBox5.setModel(dc);
            jComboBox1.setModel(dc2);
            jComboBox4.setModel(dc3);
            jComboBox7.setModel(dc5);
            jComboBox13.setModel(dc4);
            jComboBox12.setModel(dc6);
            db.kapat();
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox13 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Düzenle"));

        jLabel1.setText("Ürün Adı:");

        jLabel2.setText("Ürün Adeti:");

        jLabel3.setText("Personel Adı:");

        jLabel4.setText("İl:");

        jLabel5.setText("İlçe:");

        jLabel6.setText("Şube:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Düzenle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(93, 93, 93)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox6, 0, 218, Short.MAX_VALUE)
                                .addComponent(jComboBox4, 0, 218, Short.MAX_VALUE)
                                .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Yeni Kayıt"));

        jLabel7.setText("Ürün Adı:");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Ürün Adeti:");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("İl:");

        jLabel10.setText("İlçe:");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox10ItemStateChanged(evt);
            }
        });

        jLabel11.setText("Şube:");

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox11ItemStateChanged(evt);
            }
        });

        jLabel12.setText("Personel Adı:");

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox13ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        String il = "";
        String ilce = "";
        DB db = new DB();
        int selected = jTable1.getSelectedRow();

        try {

            ResultSet rs = db.baglan().executeQuery("Select * from subeler left join sehirler on subeler.sube_sehir_id=sehirler.sehir_id left join ilceler on subeler.sube_ilce_id=ilceler.ilce_id where sube_adi = '" + jTable1.getValueAt(selected, 1) + "'");
            rs.next();
            il = rs.getString("sehir_adi");
            ilce = rs.getString("ilce_adi");
            db.kapat();
        } catch (Exception e) {
        }

        jComboBox5.setSelectedItem(jTable1.getValueAt(selected, 0));
        int coz = Integer.valueOf("" + jTable1.getValueAt(selected, 3));
        jComboBox6.setSelectedItem(coz);
        jComboBox1.setSelectedItem(il);
        ilceDoldur();
        jComboBox2.setSelectedItem(ilce);
        subeDoldur();
        jComboBox3.setSelectedItem(jTable1.getValueAt(selected, 1));
        personelDoldur();
        jComboBox4.setSelectedItem(jTable1.getValueAt(selected, 2));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        ilceDoldur();
        subeDoldur();
        personelDoldur();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        subeDoldur();
        personelDoldur();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox10ItemStateChanged
        subeDoldur();
        personelDoldur();
    }//GEN-LAST:event_jComboBox10ItemStateChanged

    private void jComboBox13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox13ItemStateChanged
        ilceDoldur();
        subeDoldur();
        personelDoldur();
    }//GEN-LAST:event_jComboBox13ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.out.println(jComboBox3.getSelectedIndex());
        if (jComboBox2.getSelectedIndex() >= 0 && jComboBox3.getSelectedIndex() >= 0 && jComboBox4.getSelectedIndex() >= 0) {
            DB db = new DB();
            int selected = jTable1.getSelectedRow();
            String urun = urId.get(jComboBox5.getSelectedIndex());
            String adet = jComboBox6.getSelectedItem() + "";
            String sube = subeId.get(jComboBox3.getSelectedIndex());
            String pers = perId.get(jComboBox4.getSelectedIndex());

            if (selected >= 0) {

                Object[] options = {"Evet", "Hayır"};
                int response = JOptionPane.showOptionDialog(this, "Seçili kayıtı değiştirmek istediğinize emin misiniz?", "Düzenleme İşlemi",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                        options, options[0]);
                if (response == JOptionPane.YES_OPTION) {
                    String zim = zimIdler.get(selected);
                    try {

                        int res = db.baglan().executeUpdate("Update zimmetler set zim_urun_id=" + urun + " ,zim_sube_id=" + sube + ", zim_personel_id=" + pers + ",zim_urun_adet=" + Integer.parseInt(adet) + " where zim_id=" + zim);
                        if (res > 0) {

                            UIManager.put("OptionPane.okButtonText", "Tamam");
                            JOptionPane.showMessageDialog(this, "Düzenleme Başarılı");

                        }
                        db.kapat();
                        tabloDoldur();                     
                    } catch (Exception e) {

                        System.err.println("Update hatası: " + e);

                    }
                }
            } else {

                UIManager.put("OptionPane.okButtonText", "Tamam");
                JOptionPane.showMessageDialog(this, "Lütfen değiştirmek istediğiniz kayıtı tablodan seçin.");

            }
        } else {

            UIManager.put("OptionPane.okButtonText", "Tamam");
            JOptionPane.showMessageDialog(this, "Lütfen bütün alanları doldurduğunuza emin olun.");

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jComboBox2.getSelectedIndex() >= 0 && jComboBox3.getSelectedIndex() >= 0 && jComboBox4.getSelectedIndex() >= 0) {
            DB db = new DB();
            int selected = jTable1.getSelectedRow();
            if (selected >= 0) {
                Object[] options = {"Evet", "Hayır"};
                int response = JOptionPane.showOptionDialog(this, "Seçili Kayıtı Silmek İstediğinize emin misiniz?", "Silme İşlemi",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                        options, options[0]);
                if (response == JOptionPane.YES_OPTION) {
                    try {

                        int res = db.baglan().executeUpdate("Delete from zimmetler where zim_id=" + zimIdler.get(selected));
                        if (res >= 0) {

                            UIManager.put("OptionPane.okButtonText", "Tamam");
                            JOptionPane.showMessageDialog(this, "Silme işlemi başarılı");

                        }
                        db.kapat();
                        tabloDoldur();

                    } catch (Exception e) {

                        System.err.println("Silme hatası...");

                    }

                }
            } else {

                UIManager.put("OptionPane.okButtonText", "Tamam");
                JOptionPane.showMessageDialog(this, "Lütfen silmek istediğiniz kayıtı tablodan seçin.");

            }
        } else {

            UIManager.put("OptionPane.okButtonText", "Tamam");
            JOptionPane.showMessageDialog(this, "Lütfen bütün alanları doldurduğunuza emin olun.");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jComboBox10.getSelectedIndex() >= 0 && jComboBox11.getSelectedIndex() >= 0 && jComboBox12.getSelectedIndex() >= 0) {
            DB db = new DB();
            String urun = urId.get(jComboBox7.getSelectedIndex());
            String adet = jComboBox8.getSelectedItem() + "";
            String sube = subeId2.get(jComboBox11.getSelectedIndex());
            String pers = perId2.get(jComboBox12.getSelectedIndex());
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();

            try {

                int res = db.baglan().executeUpdate("Insert into zimmetler values(null," + urun + "," + sube + "," + pers + "," + adet + ",'" + dateFormat.format(date) + "')");
                if (res > 0) {

                    UIManager.put("OptionPane.okButtonText", "Tamam");
                    JOptionPane.showMessageDialog(this, "Kayıt işlemi başarılı");

                }
                db.kapat();
                tabloDoldur();

            } catch (Exception e) {

                System.err.println("Yeni Kayıt hatası: " + e);

            }
        } else {

            UIManager.put("OptionPane.okButtonText", "Tamam");
            JOptionPane.showMessageDialog(this, "Lütfen bütün alanları doldurduğunuza emin olun.");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged

        personelDoldur();

    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox11ItemStateChanged

        personelDoldur();

    }//GEN-LAST:event_jComboBox11ItemStateChanged

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("Zimmet Adı");
        dt.addColumn("Şube");
        dt.addColumn("Personel");
        dt.addColumn("Adet");
        dt.addColumn("Tarih");
        jTable1.setModel(dt);
        DB db = new DB();
        try {

            ResultSet rs = db.baglan().executeQuery("Select * from zimmetler left join personeller on personeller.personel_id=zimmetler.zim_personel_id left join subeler on zimmetler.zim_sube_id=subeler.sube_id left join urunler on zimmetler.zim_urun_id=urunler.urun_id where urun_adi like '%" + jTextField1.getText() + "%'");
            while (rs.next()) {
                zimIdler.add(rs.getString("zim_id"));
                dt.addRow(new String[]{rs.getString("urun_adi"), rs.getString("sube_adi"), rs.getString("personel_adi") + " " + rs.getString("personel_soyadi"), rs.getString("zim_urun_adet"), rs.getString("zim_tarih")});

            }
            jTable1.setModel(dt);
            db.kapat();
        } catch (Exception e) {

            System.err.println("Tablo doldurma hatası: " + e);

        }


    }//GEN-LAST:event_jTextField1KeyReleased

    public void ilceDoldur() {

        ilceId.clear();
        ilceId2.clear();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        DefaultComboBoxModel dc2 = new DefaultComboBoxModel();

        DB db = new DB();
        try {

            ResultSet rs = db.baglan().executeQuery("Select * from ilceler left join sehirler on ilceler.ilce_il_id=sehirler.sehir_id where sehir_adi='" + jComboBox1.getSelectedItem() + "'");

            while (rs.next()) {

                dc.addElement(rs.getString("ilce_adi"));
                ilceId.add(rs.getString("ilce_id"));

            }
            rs = db.baglan().executeQuery("Select * from ilceler left join sehirler on ilceler.ilce_il_id=sehirler.sehir_id where sehir_adi='" + jComboBox13.getSelectedItem() + "'");
            while (rs.next()) {

                dc2.addElement(rs.getString("ilce_adi"));
                ilceId2.add(rs.getString("ilce_id"));

            }
            jComboBox2.setModel(dc);
            jComboBox10.setModel(dc2);
            db.kapat();
        } catch (Exception e) {

        }

    }

    public void subeDoldur() {

        subeId.clear();
        subeId2.clear();
        DefaultComboBoxModel dc2 = new DefaultComboBoxModel();
        DefaultComboBoxModel dc3 = new DefaultComboBoxModel();
        DB db = new DB();
        try {

            ResultSet rs = db.baglan().executeQuery("Select * from subeler left join ilceler on subeler.sube_ilce_id=ilceler.ilce_id where ilce_adi='" + jComboBox2.getSelectedItem() + "'");
            while (rs.next()) {

                dc2.addElement(rs.getString("sube_adi"));
                subeId.add(rs.getString("sube_id"));

            }
            rs = db.baglan().executeQuery("Select * from subeler left join ilceler on subeler.sube_ilce_id=ilceler.ilce_id where ilce_adi='" + jComboBox10.getSelectedItem() + "'");
            while (rs.next()) {

                dc3.addElement(rs.getString("sube_adi"));
                subeId2.add(rs.getString("sube_id"));

            }
            jComboBox3.setModel(dc2);
            jComboBox11.setModel(dc3);
            db.kapat();
        } catch (Exception e) {
        }

    }

    public void personelDoldur() {

        perId.clear();
        perId2.clear();
        DefaultComboBoxModel dc5 = new DefaultComboBoxModel();
        DefaultComboBoxModel dc6 = new DefaultComboBoxModel();
        DB db = new DB();
        try {

            ResultSet rs = db.baglan().executeQuery("Select * from personeller left join subeler on personeller.personel_sube_id=subeler.sube_id where sube_adi='" + jComboBox3.getSelectedItem() + "'");
            while (rs.next()) {

                dc5.addElement(rs.getString("personel_adi") + " " + rs.getString("personel_soyadi"));
                perId.add(rs.getString("personel_id"));

            }
            rs = db.baglan().executeQuery("Select * from personeller left join subeler on personeller.personel_sube_id=subeler.sube_id where sube_adi='" + jComboBox11.getSelectedItem() + "'");
            while (rs.next()) {

                dc6.addElement(rs.getString("personel_adi") + " " + rs.getString("personel_soyadi"));
                perId2.add(rs.getString("personel_id"));

            }
            jComboBox4.setModel(dc5);
            jComboBox12.setModel(dc6);
            db.kapat();
        } catch (Exception e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zimmetListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zimmetListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zimmetListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zimmetListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zimmetListesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
